version: 2

jobs:
  build:
    working_directory: /go/src/github.com/gudtech/dbr-go
    docker:
      - image: circleci/golang:1.10.3
    steps:
      - checkout
      - run: dep ensure -vendor-only
      - run: go test -v -race ./...
